CREATE DATABASE IF NOT EXISTS codecraft CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE codecraft;

CREATE TABLE IF NOT EXISTS blog_posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(180) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL,
  excerpt TEXT NOT NULL, content LONGTEXT NULL, category VARCHAR(80) NOT NULL, date VARCHAR(40) NOT NULL,
  read_time VARCHAR(40) NOT NULL, image TEXT NOT NULL, author VARCHAR(120) NOT NULL, author_role VARCHAR(120) NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE, published BOOLEAN NOT NULL DEFAULT TRUE,
  published_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS projects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(180) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL,
  category VARCHAR(80) NOT NULL, description TEXT NOT NULL, long_description LONGTEXT NOT NULL, image TEXT NOT NULL,
  technologies JSON NOT NULL, results JSON NOT NULL, year VARCHAR(10) NOT NULL, client VARCHAR(180) NOT NULL,
  duration VARCHAR(80) NOT NULL, published BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS services (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(180) NOT NULL UNIQUE, icon VARCHAR(80) NOT NULL,
  title VARCHAR(180) NOT NULL, tagline VARCHAR(255) NOT NULL, description TEXT NOT NULL, features JSON NOT NULL,
  benefits JSON NOT NULL, technologies JSON NOT NULL, deliverables JSON NOT NULL, published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS team_members (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, role VARCHAR(180) NOT NULL, bio TEXT NOT NULL,
  skills JSON NOT NULL, image TEXT NOT NULL, location VARCHAR(120) NOT NULL, published BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS testimonials (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, company VARCHAR(180) NOT NULL,
  role VARCHAR(120) NOT NULL, review TEXT NOT NULL, rating TINYINT UNSIGNED NOT NULL DEFAULT 5, image TEXT NOT NULL,
  published BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS jobs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, job_key VARCHAR(120) NOT NULL UNIQUE, title VARCHAR(180) NOT NULL,
  department VARCHAR(120) NOT NULL, location VARCHAR(120) NOT NULL, type VARCHAR(80) NOT NULL, experience VARCHAR(80) NOT NULL,
  skills JSON NOT NULL, description TEXT NOT NULL, responsibilities JSON NOT NULL, posted VARCHAR(40) NOT NULL,
  published BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS contact_messages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL,
  subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, service VARCHAR(120) NULL, status ENUM('New','Read','Replied') DEFAULT 'New',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS quote_requests (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL,
  company VARCHAR(180) NULL, service VARCHAR(120) NOT NULL, budget VARCHAR(80) NULL, details TEXT NULL,
  status ENUM('Pending','Contacted','Quoted','Accepted','Rejected') DEFAULT 'Pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS job_applications (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, job_id INT UNSIGNED NULL, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL,
  resume_url TEXT NULL, message TEXT NULL, status ENUM('New','Shortlisted','Interview','Rejected','Hired') DEFAULT 'New',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, last_login TIMESTAMP NULL, role ENUM('Super Admin','Editor','Viewer') DEFAULT 'Editor', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS site_settings (
  setting_key VARCHAR(120) PRIMARY KEY, setting_value TEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
