import { useEffect, useState } from "react";

type Service = { id?: number; title: string; slug?: string; icon?: string; tagline?: string; description?: string; published?: boolean };
const blank: Service = { title: "", slug: "", icon: "Globe", tagline: "", description: "", published: true };
export default function ServiceManagement() {
  const [rows, setRows] = useState<Service[]>([]); const [query, setQuery] = useState(""); const [form, setForm] = useState<Service | null>(null); const [error, setError] = useState("");
  const load = async () => { const r = await fetch("/api/services"); if (r.ok) setRows(await r.json()); else setError("Services load nahi huay."); };
  useEffect(() => { void load(); }, []);
  const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const r = await fetch(form?.id ? `/api/services/${form.id}` : "/api/services", { method: form?.id ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, published: true, features: [], benefits: [], technologies: [], deliverables: [] }) }); if (r.ok) { setForm(null); await load(); } else setError("Service save nahi hui."); };
  const remove = async (row: Service) => { if (!row.id || !confirm(`${row.title} delete karna hai?`)) return; const r = await fetch(`/api/services/${row.id}`, { method: "DELETE" }); if (r.ok) await load(); else setError("Service delete nahi hui."); };
  return <div className="rounded-2xl border border-line bg-white shadow-card"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="font-display text-lg font-extrabold">Services</h2><p className="text-sm text-muted">Manage services dynamically</p></div><div className="flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search services" className="rounded-xl border border-line px-3 py-2 text-sm" /><button onClick={() => setForm(blank)} className="btn-primary rounded-xl px-4 py-2 text-sm">Add Service</button></div></div>{error && <p className="px-5 text-sm text-red-600">{error}</p>}<div className="divide-y divide-line">{rows.filter((r) => `${r.title} ${r.tagline || ""}`.toLowerCase().includes(query.toLowerCase())).map((row, i) => <div key={row.id} className="flex items-center gap-3 px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-ink text-xs font-bold text-white">{String(i + 1).padStart(2, "0")}</span><span className="min-w-0 flex-1"><b>{row.title}</b><small className="block text-muted">{row.tagline}</small></span><button onClick={() => setForm(row)} className="rounded-lg border border-line px-3 py-1.5 text-xs font-semibold">Edit</button><button onClick={() => remove(row)} className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-600">Delete</button></div>)}</div>{form && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6"><h3 className="text-lg font-bold">{form.id ? "Edit Service" : "Add Service"}</h3>{["title","slug","icon","tagline","description"].map((field) => <input key={field} name={field} required={field === "title"} defaultValue={(form as any)[field] || ""} placeholder={field} className="mt-3 w-full rounded-lg border border-line px-3 py-2" />)}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setForm(null)} className="rounded-lg border border-line px-4 py-2">Cancel</button><button className="btn-primary rounded-lg px-4 py-2">Save Service</button></div></form></div>}</div>;
}
